apiVersion: batch/v1
kind: CronJob #--->> cronjob level
metadata:
  creationTimestamp: null
  name: time
spec:
  startingDeadlineSeconds: 17
  jobTemplate: #--->> job template
    metadata:
      creationTimestamp: null
      name: time
    spec:
      activeDeadlineSeconds: 12
      parallelism: 5
      completions: 20
      template: #--->> pod template
        metadata:
          creationTimestamp: null
        spec: 
          containers:
          - command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
            image: busybox
            name: time
            resources: {}
          restartPolicy: Never
  schedule: '*/1 * * * *'

# cronjob.spec
# 	- startingDeadlineSeconds: 17
# 	- failedJobsHistoryLimit:
# 	- successfulJobsHistoryLimit: 3


# cronjob.spec.jobTemplate.spec
# 	- activeDeadlineSeconds: 12
# 	- parallelism: 5
# 	- completions: 20
# 	- backoffLimit: 10
